### PR TITLE
Added properties to the items

### PR DESCRIPTION
**Pull request by dragosprotung**
Addressing nelmio/NelmioApiDocBundle#1092

Issue was closed for wrong reason and without addressing the problem

### CODE REVIEW

**Comment by GuilhemN** [comment]
Since Items is an instance of Schema in swagger 3.0, I think we can stop distinguishing the two (deprecate Items in favor of Schema).

**Comment by dragosprotung** [comment]
At the moment this library is targeting version 2

**Comment by GuilhemN** [comment]
Indeed, but if we strictly followed 2.0 spec, your PR would not be mergeable as well since 2.0 spec specifies that `items` can't be a model.

**Comment by dragosprotung** [comment]
That is right :)
But i was hoping for this to get merged for the same reason GuilhemN/swagger#3 got merged

**Comment by GuilhemN** [comment]
Well if we add `properties` to Items I do no longer see the need to differenciate it from Schema. This is the biggest difference between them right now isn't it ?

**Comment by dragosprotung** [comment]
Yes. 

Shall i just make the `Schema` not final and have `Items` extend `Schema` ? This will keep BC while proving full functionality

**Comment by GuilhemN** [comment]
Yes please :)

**Comment by dragosprotung** [comment]
Done.
Fixed tests as well, in case you want to setup travis :)

**Comment by GuilhemN** [comment]
Great, thank you @dragosprotung! :)

**Pull request merged**
