### PR TITLE
Add Description to Item

### PR DESCRIPTION
**Pull request by betzholz**
Descriptions in swagger json on Items would be very nice (needed for Nelmio ApiDocBundle)

### CODE REVIEW

**Comment by GuilhemN** [comment]
Well it doesn't exist according to the spec https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#itemsObject.

**Comment by betzholz** [comment]
sure?
I found it in the Schema https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object 
there in the Definition example is a description in some items (ex. Cat property huntingSkill).
And swaggerphp does allow description by using Swagger\Annotations\ExternalDocumentation : https://github.com/zircote/swagger-php/blob/master/src/Annotations/Items.php
Also the editor from swagger parses the description.
I think its is missing in the spec.

**Comment by tamcy** [comment]
Sorry to chime in, it looks to me that there's a disagreement(?) between `zircode/swagger-php` and `exsyst/swagger`. The problem is not just a missing "description" field, but how the whole "Items Object" is implemented.

In [this commit](https://github.com/zircote/swagger-php/commit/1ce1711fb3941b7acf86d84e2de7cceb54f37075#diff-7ede314bc2cf4214000425890f75d5f5R15
) `swagger-php` changed how "Items Objects" can be formed. After the change it looks more alike the Schema Object. 

If `swagger-php`'s way is to be followed, the best patch would be to make the `Items` class to extend the `Schema` class (`Schema` needs to be non-`final`), like so:

https://gist.github.com/tamcy/beb86b024d468f6ef8e8b6831d74dd64

I found this incompatibility when investigating into the issue of not being able to define object properties under the Item object (see https://github.com/nelmio/NelmioApiDocBundle/issues/1092). But as I am new to this whole thing I'm not sure how this should be resolved.

**Comment by GuilhemN** [comment]
@betzholz had fair points, that's most likely just a lack in the specification.
Sorry for taking a decision so lately!

**Pull request merged**
